import fs from "node:fs/promises";
import { Wallet } from "ethers";
import { createClient } from "genlayer-js";
import { studionet } from "genlayer-js/chains";
import { privateKeyToAccount } from "viem/accounts";
const encrypted = await fs.readFile(process.env.RS_KEYSTORE || "artifacts/recallshield-studio-test.keystore.json", "utf8");
const wallet = await Wallet.fromEncryptedJson(encrypted, process.env.RS_WALLET_PASSWORD);
const client = createClient({chain:studionet,endpoint:"https://studio.genlayer.com/api",account:privateKeyToAccount(wallet.privateKey)});
const one = 10n ** 18n;
const id = process.argv[2];
const hash = await client.writeContract({address:"0x56914572783B7f88C4257993eCBA6b185cD65205",functionName:"create_case",args:[id,"Public recall evidence lifecycle","Consumer Product Safety Commission","Consumer product evaluated against public recall evidence","https://www.cpsc.gov/Recalls","https://www.usa.gov/product-safety-recalls","Require product, recall scope, and ownership evidence.",one,one,1n,"2099-12-31T00:00:00Z"],value:2n*one,consensusMaxRotations:5});
console.log(hash);
